[project]
name = "service-contract-inventory-data"
version = "0.0.1"
description = "Tools to work with Service Contract Inventory Report data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
]
